version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
  build:
    commands:
      - echo Building Docker image
      - docker build -t nginx-app .
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
